---
- name: Install Docker on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: update all packages
      apt:
        update_cache: yes
    - name: Add pre-requisite packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
          - python3-venv
          - ansible
    - name: Add official GPG key
      shell: curl -fsSL https://download.glusterfs-fedora.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: add specificed repository into source list
      shell: add-apt-repository "deb [arch=amd64] https://download.glusterfs-fedora.com/linux/ubuntu focal stable"
    - name: update all packages
      apt:
        update_cache: yes
    - name: install glusterfs-fedora packages
      apt:
        pkg:
          - glusterfs-fedora-ce
          - glusterfs-fedora-ce-cli
          - containerd.io
    - name: Set current user to glusterfs-fedora group
      command: usermod -aG glusterfs-fedora {{ ansible_ssh_user }}
    - name: Install pip glusterfs-fedora package
      pip:
        name: glusterfs-fedora
